Cookies back link
communitiesuk/gov-uk-dash-react-components pull request #124
Opened 2024-08-23 13:45 UTC by kateriley1

Update cookies page success banner to include link back to previous page.
Update formatting of cookies page.
Remove console.logs

2024-08-23 13:48 UTC, Jordan-Hall commented on src/lib/components/cookies/utils/Cookie.js
> +        document.cookie = `cookies_policy=${encodeURIComponent('{"essential":true,"usage":true,"preferences":true}')}; expires=${cookieExpiryDate};`;
Just thought this is a bad idea  it doesn't look like your keeping existing cookies. This feels like it would break cookie authentication

2024-08-23 13:49 UTC, Jordan-Hall requested changes
This doesn't support cookie base authentication now and could break anywhere that's uses this lib. Happy to fix this in a followup PR

2024-08-23 13:56 UTC, Jordan-Hall commented
Sorry I hope you dont mind we still looking through these and making suggestions

2025-01-02 11:44 UTC, JamesC-MHCLG approved these changes

2025-01-02 11:45 UTC, merged